"use client"
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { RecoilRoot } from 'recoil';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<RecoilRoot>
					<Toaster
						position="top-right"
						toastOptions={{
							style: {
								background: '#333',
								color: '#fff',
								fontSize: '14px',
							},
						}}
					/>
					{children}
				</RecoilRoot>
			</body>
		</html>
	);
}
